export const API_URL = "https://test.gopharm.uz/api/v1"
export const FETCH_DRUGS = "DRUGS/FETCH_DRUGS"
export const FETCH_CATEGORY = "DRUGS/FETCH_CATEGORY"
export const FETCH_SALES = "DRUGS/FETCH_SALES"
export const FETCH_DRUGS_BY_CATEGORY = "CATALOG/FETCH_DRUGS_BY_CATEGORY"
export const GET_CATEGORY_SLUG = "CATEGORY/GET_CATEGORY_SLUG"
export const FETCH_DRUG = "DRUGS/FETCH_DRUG";